version: '3.8'

services:
    dashboard:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3333:3333'
        environment:
            RUST_LOG: info
            LEPTOS_SITE_ADDR: 0.0.0.0:3333
            LEPTOS_SITE_ROOT: ./site
        restart: unless-stopped
