max_width = 120
hard_tabs = true
tab_spaces = 4
newline_style = "Auto"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = true
force_explicit_abi = true
imports_granularity = "Crate"
merge_imports = true
space_after_colon = true
struct_lit_single_line = false
trailing_comma = "Vertical"
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = true
brace_style = "PreferSameLine"
combine_control_expr = false
comment_width = 90
condense_wildcard_suffixes = true
fn_single_line = true
match_block_trailing_comma = false
struct_trailing_comma = false
struct_lit_trailing_comma = false